import:

  - &NO_SUBMIT {}

  - &SUBMIT
      actions:
        submit:
          state:  complete
      validation: {validate: true}
      phase_score_validation:
        numericality:
          allow_blank:              false
          greater_than_or_equal_to: 1
          less_than_or_equal_to:    10
          decimals:                 0
  - &SUBMIT_UNLOCK_NEXT
      actions:
        submit:
          state:  complete
          unlock: next
      validation: {validate: true}
      phase_score_validation:
        numericality:
          allow_blank:              false
          greater_than_or_equal_to: 1
          less_than_or_equal_to:    10
          decimals:                 0

  - &SUBMIT_AUTO_SCORE
      actions:
        submit:
          state:      complete
          auto_score: {min: 1, max: 3}
      validation: {validate: true}
      phase_score_validation:
        numericality:
          allow_blank:              false
          greater_than_or_equal_to: 1
          less_than_or_equal_to:    10
          decimals:                 0
  - &SUBMIT_AUTO_SCORE_UNLOCK_NEXT
      actions:
        submit:
          state:      complete
          unlock:     next
          auto_score: {min: 1, max: 3}
      validation: {validate: true}
      phase_score_validation:
        numericality:
          allow_blank:              false
          greater_than_or_equal_to: 1
          less_than_or_equal_to:    10
          decimals:                 0
