no_auto_score:
  actions: 
    submit:
      state: complete

auto_score:
  actions: 
    submit:
      state:      complete
      auto_score: {min: 1, max: 1}

auto_score_unlock_next:
  actions: 
    submit:
      state:      complete
      unlock:     next
      auto_score: {min: 1, max: 1}

validate:
  validation: {validate: true}
  phase_score_validation:
    numericality:
      allow_blank:              false
      greater_than_or_equal_to: 1
      less_than_or_equal_to:    1000
      decimals:                 0
