default: &default
  adapter:  postgresql
  encoding: utf-8
  pool:     5
  timeout:  5000
  host:     localhost
  database: <%= Rails.application.secrets.totem_database['name'] %>
  username: <%= Rails.application.secrets.totem_database['username'] %>
  password: <%= Rails.application.secrets.totem_database['password'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
