---
shared: &shared
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] %>
  totem_database:
    name: "<%= ENV['APP_TOTEM_DATABASE_NAME'] %>"
    username: "<%= ENV['APP_TOTEM_DATABASE_USERNAME'] %>"
    password: "<%= ENV['APP_TOTEM_DATABASE_PASSWORD'] %>"
  totem_oauth_providers:
    totem_oauth_1:
      _config:
        site: "<%=ENV['APP_TOTEM_OAUTH_SITE']%>"
        active: true
      thinkspace:
        client_id: "<%=ENV['APP_TOTEM_OAUTH_TOTEM_OAUTH_1_THINKSPACE_CLIENT_ID']%>"
        client_secret: "<%=ENV['APP_TOTEM_OAUTH_TOTEM_OAUTH_1_THINKSPACE_CLIENT_SECRET']%>"
        active: "<%=ENV['APP_TOTEM_OAUTH_TOTEM_OAUTH_1_THINKSPACE_ACTIVE']%>"
  aws:
    s3:
      paperclip:
        access_key: "<%= ENV['APP_AWS_S3_ACCESS_KEY'] %>"
        secret_access_key: "<%= ENV['APP_AWS_S3_SECRET_ACCESS_KEY'] %>"
        bucket_name: "<%= ENV['APP_AWS_S3_PAPERCLIP_BUCKET_NAME'] %>"
  redis_url: "<%= ENV['APP_REDIS_URL'] %>"
  smtp:
    postmark:
      username: "<%= ENV['APP_SMTP_POSTMARK_USERNAME'] %>"
      password: "<%= ENV['APP_SMTP_POSTMARK_PASSWORD'] %>"
      domain: "<%= ENV['APP_SMTP_POSTMARK_DOMAIN'] %>"

development:
  <<: *shared

test:
  <<: *shared

production:
  <<: *shared
